### create Ticket
POST {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}
Content-Type: application/json

{
  "idClient": "{{idClient}}",
  "idFly": {{idFly}}
}

### update Ticket
PUT {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}/f879d8a5-2f02-4760-a367-ed0478f637a3
Content-Type: application/json

{
  "idClient": "{{idClient}}",
  "idFly": 10
}

### getTicket
GET {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}/f879d8a5-2f02-4760-a367-ed0478f637a3

### delete ticket
DELETE {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}/f879d8a5-2f02-4760-a367-ed0478f637a3

### getPriceFlyById
GET {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}?flyId=3


### createReservation
POST {{host}}:{{port}}/{{contextPath}}/{{uriReservation}}
Content-Type: application/json

{
  "idClient": "WALA771012HCRGR054",
  "idHotel": 2,
  "totalDays": 5,
  "email": "andres@gmail.com"
}

### updateReservation
PUT {{host}}:{{port}}/{{contextPath}}/{{uriReservation}}/9081b8fd-10a0-481b-89e5-42b0a3e9ba9c
Content-Type: application/json

{
  "idClient": "{{idClient}}",
  "idHotel": 11,
  "totalDays": 5
}

### getReservation
GET {{host}}:{{port}}/{{contextPath}}/{{uriReservation}}/9081b8fd-10a0-481b-89e5-42b0a3e9ba9d

### delete reservation
DELETE {{host}}:{{port}}/{{contextPath}}/{{uriReservation}}/9081b8fd-10a0-481b-89e5-42b0a3e9ba9c

### getPriceByHotelId
GET {{host}}:{{port}}/{{contextPath}}/{{uriReservation}}?flyId=3


### getFlies
GET {{host}}:{{port}}/{{contextPath}}/{{uriFly}}
    ?page=2
    &size=5
sortType: UPPER

### getFliesByLessPrice
GET {{host}}:{{port}}/{{contextPath}}/{{uriFly}}/less-price?price=13.5

### getFliesByBetweenPrice
GET {{host}}:{{port}}/{{contextPath}}/{{uriFly}}/between-price?priceMin=10.5&priceMax=14.1

### getFliesByBetweenPrice
GET {{host}}:{{port}}/{{contextPath}}/{{uriFly}}/origin-destination?origin=Mexico&destination=Grecia


### getHotels
GET {{host}}:{{port}}/{{contextPath}}/{{uriHotel}}
    ?page=0
    &size=3
sortType: UPPER

### getHotelsByLessPrice
GET {{host}}:{{port}}/{{contextPath}}/{{uriHotel}}/less-price?price=13.5

### getHotelsByBetweenPrice
GET {{host}}:{{port}}/{{contextPath}}/{{uriHotel}}/between-price?priceMin=10.5&priceMax=14.1

### getHotelsByRating
GET {{host}}:{{port}}/{{contextPath}}/{{uriHotel}}/rating?rating=3


### getTour
GET {{host}}:{{port}}/{{contextPath}}/{{uriTour}}/1

### createTour
POST {{host}}:{{port}}/{{contextPath}}/{{uriTour}}
Content-Type: application/json

{
  "customerId": "VIKI771012HMCRG093",
  "flights": [
    {"id": 1},
    {"id": 2},
    {"id": 3},
    {"id": 4},
    {"id": 5}
  ],
  "hotels": [
    {"id": 1,"totalDays": 2},
    {"id": 10,"totalDays": 4},
    {"id": 15,"totalDays": 5}
  ]
}

### deleteTour
DELETE {{host}}:{{port}}/{{contextPath}}/{{uriTour}}/1

### getToursByRating
GET {{host}}:{{port}}/{{contextPath}}/{{uriTour}}/rating?rating=3


### addTicketFromTour
PATCH {{host}}:{{port}}/{{contextPath}}/{{uriTour}}/1/add-ticket/1

### removeTicketFromTour
PATCH {{host}}:{{port}}/{{contextPath}}/{{uriTour}}/1/remove-ticket/a377f26a-a882-4ac9-9c97-e5555e802850

### addReservationFromTour
PATCH {{host}}:{{port}}/{{contextPath}}/{{uriTour}}/1/remove-reservation/c71a86fb-728e-4fd2-ab09-33e9c79681cf

### removeReservationFromTour
PATCH {{host}}:{{port}}/{{contextPath}}/{{uriTour}}/1/add-reservation/1?totalDays=3
