### create Ticket
POST {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}
Content-Type: application/json

{
  "idClient": "{{idClient}}",
  "idFly": {{idFly}}
}

### update Ticket
PUT {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}/56467d4e-c429-47d8-aa62-aa6c03aebd55
Content-Type: application/json

{
  "idClient": "{{idClient}}",
  "idFly": 10
}

### getTicket
GET {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}/56467d4e-c429-47d8-aa62-aa6c03aebd55

### delete ticket
DELETE {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}/56467d4e-c429-47d8-aa62-aa6c03aebd55

### getPriceFlyById
GET {{host}}:{{port}}/{{contextPath}}/{{uriTicket}}?flyId=3

### create Reservation
POST {{host}}:{{port}}/{{contextPath}}/{{uriReservation}}
Content-Type: application/json

{
  "idClient": "{{idClient}}",
  "idHotel": 2,
  "totalDays": 5
}
