### create Ticket
POST {{host}}:{{port}}/{{contextPath}}/{{uri}}
Content-Type: application/json

{
  "idClient": "{{idClient}}",
  "idFly": {{idFly}}
}

### update Ticket
PUT {{host}}:{{port}}/{{contextPath}}/{{uri}}/56467d4e-c429-47d8-aa62-aa6c03aebd55
Content-Type: application/json

{
  "idClient": "{{idClient}}",
  "idFly": 10
}

### getTicket
GET {{host}}:{{port}}/{{contextPath}}/{{uri}}/56467d4e-c429-47d8-aa62-aa6c03aebd55


### delete ticket
DELETE {{host}}:{{port}}/{{contextPath}}/{{uri}}/56467d4e-c429-47d8-aa62-aa6c03aebd55

### getPriceFlyById
GET {{host}}:{{port}}/{{contextPath}}/{{uri}}?flyId=3
